{"name": "Wrong Credential Authentification Failed Test", "status": "passed", "start": 1713087206923, "stop": 1713087250986, "uuid": "b7911e48-caf0-4a98-b40c-98dc57ff72fa", "historyId": "9517ee356c092075ea995a18ebb7544f", "testCaseId": "9517ee356c092075ea995a18ebb7544f", "fullName": "test.test_user_authorization_chrome.TestUserAuth#test_invalid_creds", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_user_authorization_chrome"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "DESKTOP-84P9B6H"}, {"name": "thread", "value": "7364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_user_authorization_chrome"}]}