{"name": "Wrong Credential Authentification Failed Test", "status": "passed", "start": 1713088456530, "stop": 1713088501368, "uuid": "9a4b50b5-5bff-4912-82ab-5789dccd3379", "historyId": "9517ee356c092075ea995a18ebb7544f", "testCaseId": "9517ee356c092075ea995a18ebb7544f", "fullName": "test.test_user_authorization_chrome.TestUserAuth#test_invalid_creds", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_user_authorization_chrome"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "DESKTOP-84P9B6H"}, {"name": "thread", "value": "4352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_user_authorization_chrome"}]}