{"name": "Wrong Credential Authentification Failed Test", "status": "passed", "start": 1713099121497, "stop": 1713099168256, "uuid": "2c1b19c8-a3b8-4ff7-a2b9-ce3ff47262f1", "historyId": "9517ee356c092075ea995a18ebb7544f", "testCaseId": "9517ee356c092075ea995a18ebb7544f", "fullName": "test.test_user_authorization_chrome.TestUserAuth#test_invalid_creds", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_user_authorization_chrome"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "DESKTOP-84P9B6H"}, {"name": "thread", "value": "9024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_user_authorization_chrome"}]}